[versions]
agp = "8.2.1"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
hilt = "2.50"

core-ktx = "1.12.0"
activity-compose = "1.8.2"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
material = "1.11.0"

material3 = "1.2.0-beta02"
kotlinx-coroutines = "1.7.3"

compose-bom = "2023.10.01"
#compose = "1.5.4"
compose = "1.6.0-rc01"
constraintlayout-compose = "1.0.1"

test-junit = "1.1.5"
espresso-core = "3.5.1"
junit = "4.13.2"

room = "2.6.1"
lifecycle = "2.7.0"
glide = "4.16.0"
retrofit = "2.9.0"
okhttp = "5.0.0-alpha.12"
chucker = "4.0.0"

converter-gson = "2.9.0"
gson = "2.10.1"

navigation = "2.7.6"
lottie = "6.3.0"
volley = "1.2.1"
swiperefreshlayout = "1.1.0"

lifecycle-extensions = "2.2.0"
paging-runtime-ktx = "3.2.1"

play-services-location = "21.0.1"
shimmer = "0.5.0"

dagger = "2.50"

hilt-android = "2.50"
hilt-compiler = "1.1.0"

work-manager = "2.9.0"


[libraries]
#   implementation
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-ui-geometry = { module = "androidx.compose.ui:ui-geometry", version.ref = "compose" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "compose" }
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
androidx-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }

#  androidTestImplementation
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "test-junit" }

#  testImplementation
junit = { module = "junit:junit", version.ref = "junit" }

#  debugImplementation
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

#  ViewModel & LiveData
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

#  Room components
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

#  Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

#  Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }

#  Gson
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

#  HTTP
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

#  Chucker
chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

#  Navigation Component
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

#  Paging
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }

#  Animation
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }   # Lottie
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }  # Shimmer

#  Location Services
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }

#  RecyclerView
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }

#  Volley
volley = { module = "com.android.volley:volley", version.ref = "volley" }

#  Dagger
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }

#  Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compiler" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }

#  WorkManager
work-manager = { module = "androidx.work:work-runtime-ktx", version.ref = "work-manager" }


[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }



[bundles]
android = ["androidx-core-ktx", "androidx-activity-compose", "androidx-appcompat", "androidx-constraintlayout", "material",
    "androidx-material3", "androidx-material3-android", "androidx-material3-window-size", "kotlinx-coroutines"]

compose = ["androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling-preview", "androidx-foundation",
    "androidx-ui-geometry", "androidx-foundation-layout", "androidx-runtime-livedata", "androidx-animation-core",
    "androidx-animation", "androidx-ui-text", "androidx-ui-util", "androidx-ui-viewbinding", "androidx-material",
    "androidx-material-icons-core", "androidx-material-icons-extended", "constraintlayout-compose"]

lifecycle = ["androidx-lifecycle-runtime-ktx", "androidx-lifecycle-viewmodel-ktx", "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-livedata-ktx", "androidx-lifecycle-viewmodel-savedstate", "androidx-lifecycle-runtime-compose"]

room = ["androidx-room-runtime", "androidx-room-ktx"]
retrofit = ["retrofit", "retrofit-mock"]
gson = ["converter-gson", "gson"]
okhttp = ["okhttp", "logging-interceptor"]
navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx", "androidx-navigation-compose"]
paging = ["androidx-lifecycle-extensions", "androidx-paging-runtime-ktx"]
animation = ["lottie", "shimmer"]

android-test = ["androidx-ui-test-junit4", "androidx-espresso-core", "androidx-junit"]
debug = ["androidx-ui-tooling", "androidx-ui-test-manifest"]
test = ["junit"]

dagger = ["dagger", "dagger-android-support", "dagger-android"]

hilt = ["hilt-android", "androidx-hilt-navigation-compose"]
hilt-compiler = ["hilt-android-compiler", "hilt-compiler"]
